version: '2'
services:
  db:
    container_name: postgres
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
  api:
    container_name: api
    image: echo_reference_project:latest
    command: bash -c "sleep 1; bin/migrate -database "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" -path "db/migrations" up && bin/watcher"
    volumes:
      - .:/go/src/github.com/michaeltelford/echo_reference_project
    ports:
      - "80:8000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VERSION=1
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api
