version: '2'
services:
  db:
    container_name: postgres
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
  api:
    container_name: api
    build: .
    command: bash -c "go get github.com/canthefason/go-watcher && go install github.com/canthefason/go-watcher/cmd/watcher && watcher"
    volumes:
      - .:/go/src/github.com/michaeltelford/echo_reference_project
    ports:
      - "80:8000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app
